# ================== Spring Boot App ==================
spring.application.name=online-banking-backend


# ================== MySQL Database ==================
spring.datasource.url=jdbc:mysql://mysql-24837f40-sahamina5586-4e7f.i.aivencloud.com:18059/defaultdb?ssl-mode=REQUIRED&useSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_c_GAeAR6JBDES2JyEnZ

spring.jpa.hibernate.ddl-auto=update
server.port=8080



# ================== Driver ==================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================== JPA ==================


spring.jpa.show-sql=true

# ================== Gmail SMTP ==================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================== Fast2SMS ==================
fast2sms.api.key=${FAST2SMS_API_KEY}
